import { Montserrat, Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";

export const fontMontserrat = Montserrat ({
  subsets: ["latin"],
  display: "swap",
})

export const fontInter = Inter ({
  subsets: ["latin"],
  display: "swap",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${fontMontserrat.className} transition scroll-smooth duration-300`}>
        <Header secondaryFont={`${fontInter.className}`} />
        {children}
      </body>
    </html>
  );
}
